server:
  # Tomcat
  tomcat:
    uri-encoding: UTF-8
    max-threads: 30
    min-spare-threads: 10
  #  FIXME 配置端口
  port: 8085
  connection-timeout: 60000

spring:
  # FIXME 环境 dev|pro
  profiles:
    active: dev

  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # AOP 配置
  aop:
    auto: true
    proxy-target-class: false

  http:
    encoding:
      charset: UTF-8
      force: true
      enabled: true



