server:
  # Tomcat
  tomcat:
    uri-encoding: UTF-8
    max-threads: 30
    min-spare-threads: 10
  #  FIXME 配置端口
  port: 8084
  connection-timeout: 5000

spring:
  # FIXME 环境 dev|pro
  profiles:
    active: dev

  # jackson时间格式化
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss

  # AOP 配置
  aop:
    auto: true
    proxy-target-class: false

  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 10MB
      enabled: true



